site_name: A Lizenz
site_url: https://alizenz.afsvd.de
repo_url: https://github.com/mschwieger/alizenz
repo_name: mschwieger/alizenz
edit_uri: edit/main/docs/
theme:
    name: material
    locale: de
    palette:
        primary: black
    features:
        - navigation.tabs
plugins:
    - search:
        lang: de
    - git-revision-date-localized:
        enable_creation_date: false 
        fallback_to_build_date: false
        type: iso_datetime
markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - tables
    - attr_list
    - md_in_html
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
