site_name: AFSVHH Lehrgänge
site_url: https://clinic.afsvhh.de
repo_url: https://github.com/mschwieger/clinic
repo_name: mschwieger/clinic
theme:
    name: material
    logo: assets/images/afsvhh.png
    palette:
          primary: red
    features:
        - navigation.tabs
plugins:
    - search:
        lang: de 
markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - tables
    - attr_list
    - md_in_html
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
