site_name: AFSVHH Lehrgänge
site_url: https://clinic.afsvhh.de
repo_url: https://github.com/mschwieger/clinic
repo_name: mschwieger/clinic
edit_uri: edit/main/docs/
theme:
    name: material
    logo: assets/images/afsvhh.png
    favicon: assets/images/favicon.png
    locale: de
    palette:
        primary: red
    features:
        - navigation.tabs
plugins:
    - search:
        lang: de
    - git-revision-date-localized:
        enable_creation_date: false 
        fallback_to_build_date: false
        type: iso_datetime
markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - tables
    - attr_list
    - md_in_html
    - pymdownx.details
    - pymdownx.superfences
